prometheus:
  prometheusSpec:
    alerting:
      alertmanagers:
        - namespace: monitoramento
          name: prometheus-stack-kube-prom-alertmanager
          port: http-web

alertmanagerFiles:
  alertmanager.yml:
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'smtp.sendgrid.net:587'
      smtp_from: 'seuemail@gmail.com'
      smtp_auth_username: 'apikey'
      smtp_auth_password:
        name: alertmanager-smtp-password
        key: password

    receivers:
      - name: 'sendgrid-notifications'
        email_configs:
          - to: 'seuemail@gmail.com'
            send_resolved: true
            headers:
              subject: "Prometheus - Alerta do Cluster EKS"
            text: |
              {{ range .Alerts }}
              Alerta: {{ .Annotations.summary }} ({{ .Labels.severity }})

              Descrição: {{ .Annotations.description }}

              Detalhes:
              {{ range .Labels.SortedPairs }} - {{ .Name }}: {{ .Value }}
              {{ end }}
              {{ end }}

    route:
      group_wait: 10s
      group_interval: 2m
      receiver: 'sendgrid-notifications'
      repeat_interval: 2m
