name: 'Provisionar cluster'

on:
  workflow_dispatch: 
  push:
    branches:
      - main 

jobs:
  terraform-apply:
    runs-on: ubuntu-22.04
    steps:
      # 1️⃣ Fazer checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Configurar credenciais AWS
      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          output-env-credentials: true

      # 3️⃣ Instalar Terraform
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      # 4️⃣ Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # 5️⃣ Rodar Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      # 6️⃣ Rodar Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
